# Generated by Django 4.2.11 on 2024-05-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колличество'),
        ),
    ]
