# Generated by Django 4.2.11 on 2024-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email отправки'),
        ),
    ]
