# Generated by Django 4.2.11 on 2024-05-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_send_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='send_email',
        ),
    ]
