# Generated by Django 4.2.11 on 2024-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='send_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email отправки'),
        ),
    ]
